# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Install dependencies
      - run: yarn install --production=false

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Validate Input
      - run: yarn test-input

      # Build the complete API description
      - run: yarn build

      # Store the build artifacts 
      - store_artifacts:
          path: ./build

      # Verify the OAS2 files
      - run: yarn test-build

      # Publish to supermodel.io
      # - run: yarn publish-models

      # Publish to swaggerhub.com
      - run: yarn publish-apis

